#!/bin/bash
# setup.sh — One-time setup script for TransactiWar
# Run this ONCE before your first docker compose up.
# It auto-generates secure random passwords and writes .env for you.
# You never need to edit .env manually.

set -e

ENV_FILE=".env"

echo ""
echo "╔══════════════════════════════════════════╗"
echo "║      TransactiWar — First Time Setup     ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# ── If .env already has real passwords, don't overwrite ──────────────────────
if [ -f "$ENV_FILE" ] && ! grep -q "change_this" "$ENV_FILE"; then
    echo "✔  .env already configured — skipping password generation."
    echo "   Delete .env and re-run this script to reset credentials."
    echo ""
else
    echo "▶  Generating secure random passwords..."

    # Generate two independent 32-char random passwords
    ROOT_PASS=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 32)
    DB_PASS=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 32)

    cat > "$ENV_FILE" <<EOF
# ─── Auto-generated by setup.sh — do not edit manually ───────────────────────
# Re-run setup.sh to regenerate credentials (this will wipe the database).

MYSQL_ROOT_PASSWORD=${ROOT_PASS}
MYSQL_DATABASE=transactiwar
MYSQL_USER=twuser
MYSQL_PASSWORD=${DB_PASS}

# These must match MYSQL_USER and MYSQL_PASSWORD above
DB_HOST=db
DB_NAME=transactiwar
DB_USER=twuser
DB_PASS=${DB_PASS}
APP_ENV=production
EOF

    echo "✔  .env written with auto-generated passwords."
fi

# ── Clean up any leftover containers from previous runs ──────────────────────
echo "▶  Removing any leftover containers..."
docker rm -f transactiwar_web transactiwar_db transactiwar_caddy 2>/dev/null || true

# ── Build and start ───────────────────────────────────────────────────────────
echo "▶  Building and starting containers..."
docker compose up --build -d

# ── Wait for healthy state ────────────────────────────────────────────────────
echo "▶  Waiting for database to be ready..."
for i in $(seq 1 30); do
    if docker exec transactiwar_db mysqladmin ping -h localhost --silent 2>/dev/null; then
        echo "✔  Database is ready."
        break
    fi
    printf "   Still waiting... (%d/30)\r" "$i"
    sleep 2
done

# ── Trust Caddy CA ────────────────────────────────────────────────────────────
echo "▶  Trusting Caddy's local CA (browser cert)..."
docker exec transactiwar_caddy caddy trust 2>/dev/null && echo "✔  Caddy CA trusted." || echo "⚠  caddy trust failed — you may need to click 'Advanced → Proceed' in the browser."

# ── Seed accounts ─────────────────────────────────────────────────────────────
echo "▶  Creating test accounts..."
docker exec transactiwar_web php /var/www/html/create_accounts.php

# ── Import Phase2 CSV users ───────────────────────────────────────────────────
echo "▶  Importing Phase2 CSV accounts..."
docker exec transactiwar_web php /var/www/html/import_csv.php

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════╗"
echo "║           Setup Complete!                ║"
echo "╚══════════════════════════════════════════╝"
echo ""
echo "  Open:  https://localhost"
echo ""
echo "  Test accounts:"
echo "    alice   / Alice@12345!"
echo "    bob     / Bob@12345!"
echo "    charlie / Charlie@12345!"
echo ""
echo "  To stop:       docker compose down"
echo "  To full reset: docker compose down -v && bash setup.sh"
echo ""
